using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.SqlClient;
using System.Windows.Forms;

namespace BTL_QuanLyBanThuoc
{
    public partial class fLoaiHang : Form
    {
        public fLoaiHang()
        {
            InitializeComponent();
        }


        private string GetAutoGeneratedID()
        {
            string Ma = "";

            using (SqlConnection connection = new SqlConnection(dbConnect.ConnectionString))
            {
                connection.Open();

                SqlCommand command = new SqlCommand("SELECT dbo.AUTO_IDLH()", connection);
                Ma = command.ExecuteScalar().ToString();
            }

            return Ma;
        }


        //######################################### SỰ KIỆN CHỨC NĂNG ############################################################################

        //--------------------------BUTTON THÊM MỚI--------------------------
        private void btnThem_Click(object sender, System.EventArgs e)
        {
            string sMaLH = GetAutoGeneratedID(); // Gọi function từ cơ sở dữ liệu để lấy mã loại hàng mới
            txbMaLH.Text = sMaLH; // Gán mã loại hàng vào ô textbox cho Mã
            txbMaLH.ReadOnly = true;
        }



        //--------------------------BUTTON LƯU--------------------------
        private void btnLuuLH_Click(object sender, System.EventArgs e)
        {
            string sMaLH, sTenLH;
            sMaLH = txbMaLH.Text;
            sTenLH = txbTenLH.Text;
            int iTrangThai = 0;

            ThuVienChung tv = new ThuVienChung();
            string Tencu = tv.LayGiaTriCu<string>("tblLoaiHang", "sTenLH", "sMaLH", sMaLH);

            bool Ma = ThuVienChung.CheckExsit("tblLoaiHang", "sMaLH", sMaLH);
            if (Ma != true)
            {
                //btnSuaNCC.Visible = false;
                //btnThemNCC.Visible = true;
                //btnThem(btnThemNCC, EventArgs.Empty);
                if(txbMaLH.Text != "" && txbTenLH.Text != "")
                {
                    iTrangThai = 1;
                }
                bool t = LoaiHang.ThemLH(sMaLH, sTenLH, iTrangThai);
                if (t)
                {
                    MessageBox.Show("Thêm thành công!", "Thông Báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    ThuVienChung.Hien("vwLoaiHang", viewLH);
                }
                else
                {
                    MessageBox.Show("Loại hàng đã tồn tại! Thêm thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            else if (Ma == true && sTenLH != Tencu)
            {
                // Hiển thị cảnh báo thông tin chỉnh sửa
                List<string> thongTinChinhSua = new List<string>();

                if (sTenLH != Tencu)
                { thongTinChinhSua.Add("Tên mặt hàng từ " + Tencu + " thành " + sTenLH + ","); }

                string message = "Mặt hàng tồn tại.Bạn chắc chắn muốn thực hiện sửa đổi loại hàng " + sMaLH + ":\n" +
                                 string.Join("\n", thongTinChinhSua.ToArray()) + "\nKhông thể hoàn tác sau khi sửa đổi.";

                DialogResult result = MessageBox.Show(message, "Xác nhận sửa đổi", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
                if (result == DialogResult.Yes)
                {
                    bool s = LoaiHang.SuaLH(sMaLH, sTenLH);
                    if (s)
                    {
                        MessageBox.Show("Sửa thành công!", "OK", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ThuVienChung.Hien("vwLoaiHang", viewLH);
                    }
                    else
                    { MessageBox.Show("Sửa thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error); }
                }
            }
        }

        //--------------------------BUTTON XÓA--------------------------
        private void btnXoaLH_Click(object sender, System.EventArgs e)
        {
            ThuVienChung t = new ThuVienChung();
            string sMaLH = txbMaLH.Text;
            int iTrangThai = t.LayGiaTriCu<int>("tblLoaiHang", "iTrangThai", "sMaLH", sMaLH);
            if (iTrangThai != 2)
            {
                DialogResult result = MessageBox.Show("Bạn chắc chắn muốn xóa loại hàng " + sMaLH + " và các Mặt Hàng trong đó?", "Xác Nhận", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                if (result == DialogResult.Yes)
                {
                    bool i = ThuVienChung.Xoa("tblLoaiHang", "sMaLH", sMaLH);
                    if (i)
                    {
                        MessageBox.Show("Xóa thành công!", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ThuVienChung.Hien("vwLoaiHang", viewLH);
                    }
                    else
                    {
                        MessageBox.Show("Xóa thất bại!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            else
            {
                MessageBox.Show("Loại hàng đã ở trạng thái ngừng bán!", "Lỗi", MessageBoxButtons.RetryCancel, MessageBoxIcon.Error);
            }
        }

        //--------------------------BUTTON TÌM KIẾM--------------------------
        private void txbTimLH_TextChanged(object sender, System.EventArgs e)
        {
            string inputValue = txbTimLH.Text;
            ThuVienChung.TimKiem("TimKiemLH", "@inputValue", inputValue, viewLH);
        }



        //--------------------------PHÂN LOẠI--------------------------
        private void DieuKienHienThi()
        {
            if (ckbHienHanhLH.Checked && ckbLuuNhapLH.Checked && !ckbDungBanLH.Checked)
            {
                ThuVienChung.Hienn("vwLoaiHang", " where  [Trạng Thái] = 1 or [Trạng Thái] = 0 ", viewLH);
            }
            else if (ckbHienHanhLH.Checked && ckbDungBanLH.Checked && !ckbLuuNhapLH.Checked)
            {
                ThuVienChung.Hienn("vwLoaiHang", " where  [Trạng Thái] = 1 or [Trạng Thái] = 2 ", viewLH);
            }
            else if (ckbDungBanLH.Checked && ckbLuuNhapLH.Checked && !ckbHienHanhLH.Checked)
            {
                ThuVienChung.Hienn("vwLoaiHang", " where  [Trạng Thái] = 0 or [Trạng Thái] = 2 ", viewLH);
            }
            else if (ckbHienHanhLH.Checked && ckbLuuNhapLH.Checked && ckbDungBanLH.Checked)
            {
                ThuVienChung.Hienn("vwLoaiHang", "", viewLH);
            }
        }

        private void ckbHienHanhLH_CheckedChanged(object sender, System.EventArgs e)
        {
            if (ckbHienHanhLH.Checked && !ckbLuuNhapLH.Checked && !ckbDungBanLH.Checked)
            {
                ThuVienChung.Hienn("vwLoaiHang", " where  [Trạng Thái] = 1 ", viewLH);
            }
            else
            {
                DieuKienHienThi();
            }
        }

        private void ckbLuuNhapLH_CheckedChanged(object sender, System.EventArgs e)
        {
            if (ckbLuuNhapLH.Checked && !ckbHienHanhLH.Checked && !ckbDungBanLH.Checked)
            {
                ThuVienChung.Hienn("vwLoaiHang", " where  [Trạng Thái] = 0 ", viewLH);
            }
            else
            {
                DieuKienHienThi();
            }
        }

        private void ckbDungBanLH_CheckedChanged(object sender, System.EventArgs e)
        {
            if (ckbDungBanLH.Checked && !ckbLuuNhapLH.Checked && !ckbHienHanhLH.Checked)
            {
                ThuVienChung.Hienn("vwLoaiHang", " where  [Trạng Thái] = 2 ", viewLH);
            }
            else
            {
                DieuKienHienThi();
            }
        }

        //######################################### SỰ KIỆN MÀN HÌNH ############################################################################

        //----------------------LOAD CỦA FORM LOẠI HÀNG-----------------------------------------
        private void fLoaiHang_Load(object sender, System.EventArgs e)
        {
            ThuVienChung.Hien("vwLoaiHang", viewLH);
        }

        ////-----------------------RELOAD-------------------------------
        private void viewLH_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            txbMaLH.Text = viewLH.CurrentRow.Cells["Mã Loại Hàng"].Value.ToString();
            txbTenLH.Text = viewLH.CurrentRow.Cells["Tên Loại Hàng"].Value.ToString();
        }

        ////-----------------------HIỂN THỊ LẠI CỘT TRẠNG THÁI-------------------------------
        private void viewLH_CellFormatting(object sender, DataGridViewCellFormattingEventArgs e)
        {
            if (this.viewLH.Columns[e.ColumnIndex].Name == "Trạng Thái")
            {
                if (e.Value != null)
                {
                    int trangThai = int.Parse(e.Value.ToString());
                    if (trangThai == 1)
                    {
                        e.Value = "Hiện hành";
                    }
                    else if (trangThai == 0)
                    {
                        e.Value = "Lưu nháp";
                    }
                    else if (trangThai == 2)
                    {
                        e.Value = "Dừng bán";
                    }
                    e.FormattingApplied = true;
                }
            }
        }
    }
}
